version: "3.9"
services:
  app:
    build: .
    image: "netquest:local"
    command: uvicorn app.main:app --host 0.0.0.0 --port=8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
  
  database:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
