version: "3.9"
services:
  app:
    build: .
    image: "netquest:local"
    command: uvicorn main:app --host 0.0.0.0 --port=8000 --reload
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
